name: latinize
version: 0.1.0-nullsafety.0

description: Simple library to convert accents (diacritics) from strings to latin characters.
homepage: https://github.com/lucasmafra/latinize

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety
