version: 2

jobs_defaults: &defaults
  docker:
    - image: google/dart
  working_directory: ~/repo

jobs:
  deps:
    <<: *defaults
    steps:
        - checkout
        - run:
            name: Download dependencies
            command: pub get
        - save_cache:
            paths:
              - pubspec.lock
              - .packages
              - .dart_tool
              - ~/.pub-cache
            key: v2-pubcache-{{ checksum "pubspec.yaml" }}

  test:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            key: v2-pubcache-{{ checksum "pubspec.yaml" }}
        - run:
            name: Lint
            command: bash -c '[[ "$(dartfmt -n . | wc -l)" -eq "0" ]]'
        - run:
            name: Dartanalyze
            command: dartanalyzer --fatal-infos --fatal-warnings .
        - run:
            name: Test
            command: pub run test

  deploy:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            key: v2-pubcache-{{ checksum "pubspec.yaml" }}
        - run:
            name: Write credentials
            command: echo "{\"accessToken\":\"$ACCESS_TOKEN\",\"refreshToken\":\"$REFRESH_TOKEN\",\"tokenEndpoint\":\"https://accounts.google.com/o/oauth2/token\",\"scopes\":[\"https://www.googleapis.com/auth/plus.me\",\"https://www.googleapis.com/auth/userinfo.email\"],\"expiration\":$EXPIRATION}" > ~/.pub-cache/credentials.json
        - run:
            name: Deploy to pub.dartlang.org
            command: echo y | pub publish

workflows:
  version: 2
  keep-it-green:
    jobs:
      - deps
      - test:
          requires:
            - deps
  test-and-deploy:
    jobs:
      - deps:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - deps
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
